# Generated by Django 3.0.2 on 2020-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('end_lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('start_long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('end_long', models.DecimalField(decimal_places=5, max_digits=8)),
                ('severity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField()),
                ('name', models.TextField()),
                ('query_parameter', models.TextField()),
            ],
        ),
    ]
