# Generated by Django 3.0.2 on 2020-01-26 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QueryItems',
            new_name='QueryItem',
        ),
    ]
